### ISSUE TITLE
removal of  ', /* ssi_menubar(), */ '

### ISSUE THREAD

**Issue by illori** [SimpleMachines/smfcurve#11]
why was this removed? it was added so that people that are not very tech savvy can take advantage of SSI and add the menubar. i would recommend adding it back, it does not take up a lot of space.

https://github.com/SimpleMachines/smfcurve/pull/10/commits/6afb73af7a224baa8624cfbc0dd527845ad2ca5d#diff-65df87e8ee0df805ddb44d513a3b636cL89

**Comment by jdarwood007** [comment]
It was changed to make the skin easier to add changes.  Specifically I added these changes so its easier to develop and update from our own wiki skin changes.

This can easily be added in by adding a function to the class:
````
function customTopSection()
{
    ssi_menubar();
}
````

There is a way to tie into this skin as a "base" skin and the "sm site wiki" skin extends it.  Right now changes made to this skin also have to be synced to our site and adjusted to work with our changes.

We can continue to add these in wherever it makes sense.  Others who use this and add in their own changes will find this handy to keep their addons/changes from being lost with updates.
